export const FETCH = 'FETCH';
export const SET_ANSWERS = 'SET_ANSWERS';
export const INITIAL_QUIZZES = 'INITIAL_QUIZZES';
export const INCREASE_CURRENT_INDEX = 'INCREASE_CURRENT_INDEX';
export const SET_CORRECT_ANSWER = 'SET_CORRECT_ANSWER';
export const SET_INCORRECT_ANSWER = 'SET_INCORRECT_ANSWER';
